version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locker_room_talk_dev
      MYSQL_USER: lrt_user
      MYSQL_PASSWORD: lrt_pw
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge