spring:
  application:
    name: locker-room-talk
  profiles:
    active: local
  datasource:
    name: lockerRoomTalkDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.hbm2ddl.schema-generation.foreign-key-handling-mode: skip

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/locker_room_talk_dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: lrt_user
    password: lrt_pw
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

---

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure.sql.init.ScriptDatabaseInitializer: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

